project_id = "ytophmlfbrnhmqtwpijn"

[functions.invite-user]
verify_jwt = true

[functions.invalidate-work-order]
verify_jwt = true

[functions.delete-work-order]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.send-email-jobs]
verify_jwt = false

[functions.get-delivery-note-pdf]
verify_jwt = true

[functions.compute-film-job]
verify_jwt = true

[functions.open-film-work-order]
verify_jwt = true

[functions.send-delivery-note]
verify_jwt = true

[functions.drain-email-outbox]
verify_jwt = false

[functions.print-work-order]
verify_jwt = true

[functions.notify-priority-change]
verify_jwt = true

[functions.create-client-portal-user]
verify_jwt = true

[functions.generate-client-delivery-report]
verify_jwt = true
