project_id = "ytophmlfbrnhmqtwpijn"

[functions.invite-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.send-email-jobs]
verify_jwt = false

[functions.get-delivery-note-pdf]
verify_jwt = true