// Newsletter za Brand Box: obaveštenje da svaki komercijalista dobija otpremnicu
// na svoj mail čim se posao završi.
const LOGO_WHITE =
  "https://ytophmlfbrnhmqtwpijn.supabase.co/storage/v1/object/public/newsletter-assets/gama-united-white.png";
const BRANDBOX_LOGO =
  "https://ytophmlfbrnhmqtwpijn.supabase.co/storage/v1/object/public/newsletter-assets/brandbox-logo.png";

export const BRANDBOX_HTML = `<!doctype html>
<html lang="sr" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="x-apple-disable-message-reformatting"><title>Otpremnica stiže direktno na Vaš mail</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<style>html,body{margin:0!important;padding:0!important;width:100%!important}*{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}table,td{border-collapse:collapse!important}img{border:0;outline:0;text-decoration:none;display:block}a{text-decoration:none}@media screen and (max-width:660px){.shell{width:100%!important}.px{padding-left:24px!important;padding-right:24px!important}.hero{padding-top:42px!important;padding-bottom:44px!important}.hero-title{font-size:31px!important;line-height:37px!important;letter-spacing:-.6px!important}.stack,.stack>tbody,.stack>tbody>tr,.stack>tbody>tr>td{display:block!important;width:100%!important;box-sizing:border-box!important}.gap{height:12px!important;padding:0!important}.btn a{display:block!important;text-align:center!important}}</style></head>
<body style="margin:0;padding:0;background:#f5f7fa;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#081538;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">Od sada svaki poručilac iz Brand Box-a dobija otpremnicu na svoj mail, u trenutku kada posao bude završen.</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f5f7fa;"><tr><td align="center" style="padding:26px 12px;">
<table role="presentation" class="shell" width="640" cellspacing="0" cellpadding="0" border="0" style="width:640px;max-width:640px;background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 16px 50px rgba(8,21,56,.11);">

<tr><td class="px" style="padding:23px 42px;background:#1b2b50;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td valign="middle"><img src="${LOGO_WHITE}" width="150" alt="Gama United" style="display:block;width:150px;max-width:150px;height:auto;border:0;"></td><td align="right" valign="middle"><span style="display:inline-block;padding:8px 13px;border:1px solid rgba(255,255,255,.18);border-radius:999px;color:#d8e0ec;font-size:11px;line-height:14px;font-weight:700;letter-spacing:1px;text-transform:uppercase;">Za Brand Box</span></td></tr></table></td></tr>

<tr><td class="px hero" style="padding:52px 42px 54px;background-color:#081538;background-image:linear-gradient(90deg,rgba(8,21,56,.98) 0%,rgba(8,21,56,.92) 55%,rgba(8,21,56,.55) 100%);"><div style="display:inline-block;padding:7px 14px;border:1px solid rgba(243,146,55,.45);border-radius:999px;background:rgba(255,255,255,.05);color:#f39237;font-size:11px;line-height:14px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase;">Novo — samo za Vas</div><h1 class="hero-title" style="margin:21px 0 15px;max-width:520px;font-size:40px;line-height:47px;letter-spacing:-1.1px;color:#ffffff;font-weight:800;">Vaša otpremnica. Vaš mail. Istog trenutka.</h1><p style="margin:0;max-width:480px;font-size:17px;line-height:27px;color:#d7deea;">Od sada svaki poručilac iz Brand Box-a dobija otpremnicu direktno na svoju adresu — čim posao izađe iz produkcije. Bez čekanja, bez prosleđivanja, bez zatrpanog zajedničkog inboxa.</p></td></tr>

<tr><td align="center" style="padding:30px 42px 6px;background:#ffffff;"><table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td align="center" valign="middle" style="padding:0 16px;"><img src="${BRANDBOX_LOGO}" width="180" alt="Brand Box" style="display:block;width:180px;max-width:180px;height:auto;border:0;"></td><td valign="middle" style="padding:0 6px;font-size:22px;line-height:22px;color:#c3cbd8;font-weight:700;">&times;</td><td align="center" valign="middle" style="padding:0 16px;"><img src="${LOGO_WHITE}" width="150" alt="Gama United" style="display:block;width:150px;max-width:150px;height:auto;border:0;background:#1b2b50;padding:10px 12px;border-radius:10px;"></td></tr></table><p style="margin:18px 0 0;font-size:14px;line-height:22px;color:#8892a4;">Rešenje napravljeno po meri Vašeg tima.</p></td></tr>

<tr><td class="px" style="padding:34px 42px 16px;background:#ffffff;"><div style="font-size:11px;line-height:14px;color:#e07b1f;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;">Šta smo uradili</div><h2 style="margin:9px 0 12px;font-size:27px;line-height:34px;letter-spacing:-.6px;color:#081538;">Otpremnica ide onome ko je posao i poručio</h2><p style="margin:0;font-size:15px;line-height:24px;color:#657087;">U naš sistem smo uneli sve komercijaliste iz Brand Box-a. Kada otvaramo radni nalog, biramo osobu koja je posao poručila — i obaveštenje sa otpremnicom u PDF-u stiže isključivo njoj.</p></td></tr>

<tr><td class="px" style="padding:16px 42px 40px;background:#ffffff;"><table role="presentation" class="stack" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>
<td width="49%" valign="top" style="padding:22px;background:#fbfcfe;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#fdefe0;color:#c96a12;text-align:center;font-size:14px;line-height:37px;font-weight:800;">01</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">Svako svoju otpremnicu</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Više nema prosleđivanja — dokument stiže tačno onome kome treba.</div></td><td class="gap" width="2%">&nbsp;</td>
<td width="49%" valign="top" style="padding:22px;background:#fbfcfe;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#fdefe0;color:#c96a12;text-align:center;font-size:14px;line-height:37px;font-weight:800;">02</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">U realnom vremenu</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Mail kreće automatski u sekundi kada nalog bude zatvoren.</div></td></tr><tr><td colspan="3" height="12" style="height:12px;line-height:12px;font-size:0;">&nbsp;</td></tr><tr>
<td width="49%" valign="top" style="padding:22px;background:#fbfcfe;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#fdefe0;color:#c96a12;text-align:center;font-size:14px;line-height:37px;font-weight:800;">03</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">Uredan inbox uprave</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Zajednička adresa se više ne zatrpava obaveštenjima za svaki posao.</div></td><td class="gap" width="2%">&nbsp;</td>
<td width="49%" valign="top" style="padding:22px;background:#fbfcfe;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#fdefe0;color:#c96a12;text-align:center;font-size:14px;line-height:37px;font-weight:800;">04</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">PDF spreman za arhivu</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Otpremnica je u prilogu maila — spremna za štampu i knjiženje.</div></td></tr></table></td></tr>

<tr><td class="px" style="padding:42px;background:#f8fafc;"><div style="font-size:11px;line-height:14px;color:#00a8d3;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;">Kako to izgleda u praksi</div><h2 style="margin:9px 0 26px;font-size:27px;line-height:34px;letter-spacing:-.6px;color:#081538;">Tri koraka, bez ijednog Vašeg klika</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#081538;color:#ffffff;text-align:center;font-size:13px;line-height:34px;font-weight:800;">1</div></td><td valign="top" style="padding-bottom:18px;"><div style="font-size:16px;line-height:22px;color:#081538;font-weight:800;">Pošaljete posao kao i do sada</div><div style="margin-top:4px;font-size:14px;line-height:22px;color:#707b90;">Mailom ili dogovorom sa našom pripremom — ništa se ne menja u Vašem radu.</div></td></tr>
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#081538;color:#ffffff;text-align:center;font-size:13px;line-height:34px;font-weight:800;">2</div></td><td valign="top" style="padding-bottom:18px;"><div style="font-size:16px;line-height:22px;color:#081538;font-weight:800;">Mi Vas vežemo za nalog</div><div style="margin-top:4px;font-size:14px;line-height:22px;color:#707b90;">Na radnom nalogu se bira ime poručioca iz Brand Box-a i njegova mail adresa.</div></td></tr>
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#f39237;color:#0d1b3d;text-align:center;font-size:13px;line-height:34px;font-weight:800;">3</div></td><td valign="top"><div style="font-size:16px;line-height:22px;color:#081538;font-weight:800;">Posao gotov &rarr; otpremnica na Vaš mail</div><div style="margin-top:4px;font-size:14px;line-height:22px;color:#707b90;">Sa brojem naloga, specifikacijom i PDF otpremnicom u prilogu.</div></td></tr></table></td></tr>



<tr><td class="px" style="padding:0 42px 40px;background:#ffffff;"><div style="padding:22px;border:1px solid #e7ebf2;border-radius:18px;background:#fbfcfe;"><div style="font-size:15px;line-height:24px;color:#3b4557;">Ako neko iz Vašeg tima nije na listi ili želite da promenite adresu na koju stižu otpremnice — javite nam i dodaćemo ga isti dan.</div><div style="margin-top:14px;font-size:14px;line-height:22px;color:#081538;font-weight:700;">Gama United &middot; 063 / 237 - 226 &middot; <a href="mailto:office@gamaunited.rs" style="color:#0072a3;">office@gamaunited.rs</a></div></div></td></tr>

<tr><td class="px" style="padding:28px 42px 34px;background:#1b2b50;"><img src="${LOGO_WHITE}" width="130" alt="Gama United" style="display:block;width:130px;max-width:130px;height:auto;border:0;margin-bottom:14px;"><div style="font-size:13px;line-height:21px;color:#aebbd0;">Hvala Vam na poverenju i na svakom zajedničkom poslu.<br>Vaš tim — Gama United</div><div style="margin-top:14px;font-size:11px;line-height:18px;color:#7d8ba5;">Gama United d.o.o. &middot; Otona Župančiča, Beograd<!-- UNSUB_PLACEHOLDER --></div></td></tr>

</table></td></tr></table></body></html>`;
