// Auto-generated raw HTML template for the "Reklamacije preko portala" newsletter.
// Adapted to Gama United newsletter standards: hosted white logo, Arial stack,
// UNSUB_PLACEHOLDER in footer, single accent palette (navy #081538 + cyan #00caf8).
const LOGO_WHITE =
  "https://ytophmlfbrnhmqtwpijn.supabase.co/storage/v1/object/public/newsletter-assets/gama-united-white.png";

export const REKLAMACIJE_HTML = `<!doctype html>
<html lang="sr" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="x-apple-disable-message-reformatting"><title>Nova mogućnost: reklamacije preko portala</title>
<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml><![endif]-->
<style>html,body{margin:0!important;padding:0!important;width:100%!important}*{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}table,td{border-collapse:collapse!important}img{border:0;outline:0;text-decoration:none;display:block}a{text-decoration:none}@media screen and (max-width:660px){.shell{width:100%!important}.px{padding-left:24px!important;padding-right:24px!important}.hero{padding-top:42px!important;padding-bottom:45px!important}.hero-title{font-size:32px!important;line-height:38px!important;letter-spacing:-.6px!important}.stack,.stack>tbody,.stack>tbody>tr,.stack>tbody>tr>td{display:block!important;width:100%!important;box-sizing:border-box!important}.gap{height:12px!important;padding:0!important}.btn a{display:block!important;text-align:center!important}}</style></head>
<body style="margin:0;padding:0;background:#f5f7fa;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;color:#081538;">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">Prijavite reklamaciju direktno preko Gama United portala i pratite rešavanje u realnom vremenu.</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f5f7fa;"><tr><td align="center" style="padding:26px 12px;">
<table role="presentation" class="shell" width="640" cellspacing="0" cellpadding="0" border="0" style="width:640px;max-width:640px;background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 16px 50px rgba(8,21,56,.11);">

<tr><td class="px" style="padding:23px 42px;background:#1b2b50;border-bottom:1px solid rgba(255,255,255,.10);"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td valign="middle"><img src="${LOGO_WHITE}" width="150" alt="Gama United" style="display:block;width:150px;max-width:150px;height:auto;border:0;"></td><td align="right" valign="middle"><span style="display:inline-block;padding:8px 13px;border:1px solid rgba(255,255,255,.18);border-radius:999px;color:#d8e0ec;font-size:11px;line-height:14px;font-weight:700;letter-spacing:1px;text-transform:uppercase;">Klijentski portal</span></td></tr></table></td></tr>

<tr><td class="px hero" style="padding:55px 42px 58px;background-color:#081538;background-image:linear-gradient(90deg,rgba(8,21,56,.98) 0%,rgba(8,21,56,.90) 48%,rgba(8,21,56,.35) 100%),url('https://gamaunited.rs/assets/hero-maslacak-DL4rbA2N.jpg');background-size:cover;background-position:center right;"><div style="display:inline-block;padding:7px 14px;border:1px solid rgba(0,202,248,.38);border-radius:999px;background:rgba(255,255,255,.05);color:#00caf8;font-size:11px;line-height:14px;font-weight:700;letter-spacing:1.6px;text-transform:uppercase;">Nova funkcionalnost portala</div><h1 class="hero-title" style="margin:21px 0 15px;max-width:500px;font-size:42px;line-height:48px;letter-spacing:-1.2px;color:#ffffff;font-weight:800;">Recite nam kada nešto nije kako treba.</h1><p style="margin:0 0 29px;max-width:470px;font-size:17px;line-height:27px;color:#d7deea;">Od sada reklamaciju možete prijaviti direktno preko korisničkog portala — brzo, jednostavno i uz potpun uvid u tok rešavanja.</p><table role="presentation" class="btn" cellspacing="0" cellpadding="0" border="0"><tr><td bgcolor="#00caf8" style="border-radius:999px;"><a href="https://gamaunited.rs/portal-za-klijente" target="_blank" style="display:inline-block;padding:15px 24px;color:#061433;font-size:15px;line-height:20px;font-weight:800;">Otvorite korisnički portal&nbsp;&nbsp;&rarr;</a></td></tr></table></td></tr>

<tr><td class="px" style="padding:45px 42px 17px;background:#f8fafc;"><div style="font-size:11px;line-height:14px;color:#00a8d3;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;">Sve na jednom mestu</div><h2 style="margin:9px 0 12px;font-size:28px;line-height:35px;letter-spacing:-.6px;color:#081538;">Šta možete da prijavite?</h2><p style="margin:0;font-size:15px;line-height:24px;color:#657087;">Svaka primedba stiže direktno do odgovorne osobe. Ako niste sigurni koju kategoriju da izaberete, označite „Ostalo“.</p></td></tr>

<tr><td class="px" style="padding:13px 42px 42px;background:#f8fafc;"><table role="presentation" class="stack" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>
<td width="49%" valign="top" style="padding:22px;background:#ffffff;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#e8faff;color:#008eb5;text-align:center;font-size:14px;line-height:37px;font-weight:800;">01</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">Posao ili nalog</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Ako nešto nije urađeno prema dogovorenoj specifikaciji.</div></td><td class="gap" width="2%">&nbsp;</td>
<td width="49%" valign="top" style="padding:22px;background:#ffffff;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#e8faff;color:#008eb5;text-align:center;font-size:14px;line-height:37px;font-weight:800;">02</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">Kvalitet rada</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Primedbe na kvalitet štampe, ploča ili filma.</div></td></tr><tr><td colspan="3" height="12" style="height:12px;line-height:12px;font-size:0;">&nbsp;</td></tr><tr>
<td width="49%" valign="top" style="padding:22px;background:#ffffff;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#e8faff;color:#008eb5;text-align:center;font-size:14px;line-height:37px;font-weight:800;">03</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">Komunikacija</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Ako odnos ili usluga nisu bili na očekivanom nivou.</div></td><td class="gap" width="2%">&nbsp;</td>
<td width="49%" valign="top" style="padding:22px;background:#ffffff;border:1px solid #e7ebf2;border-radius:20px;"><div style="width:37px;height:37px;border-radius:50%;background:#e8faff;color:#008eb5;text-align:center;font-size:14px;line-height:37px;font-weight:800;">04</div><div style="margin-top:15px;font-size:17px;line-height:22px;color:#081538;font-weight:800;">Rok ili ostalo</div><div style="margin-top:6px;font-size:13px;line-height:20px;color:#707b90;">Kašnjenje isporuke ili bilo koja druga primedba.</div></td></tr></table></td></tr>

<tr><td class="px" style="padding:43px 42px;background:#ffffff;"><div style="font-size:11px;line-height:14px;color:#00a8d3;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;">Četiri kratka koraka</div><h2 style="margin:9px 0 27px;font-size:28px;line-height:35px;letter-spacing:-.6px;color:#081538;">Kako funkcioniše?</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#081538;color:#ffffff;text-align:center;font-size:13px;line-height:34px;font-weight:800;">1</div></td><td style="padding:4px 0 21px;font-size:15px;line-height:23px;color:#657087;"><strong style="color:#081538;">Otvorite „Reklamacije“</strong> i kliknite na „Nova reklamacija“.</td></tr>
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#081538;color:#ffffff;text-align:center;font-size:13px;line-height:34px;font-weight:800;">2</div></td><td style="padding:4px 0 21px;font-size:15px;line-height:23px;color:#657087;"><strong style="color:#081538;">Izaberite tip i ozbiljnost</strong> i, po potrebi, povežite konkretan nalog.</td></tr>
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#081538;color:#ffffff;text-align:center;font-size:13px;line-height:34px;font-weight:800;">3</div></td><td style="padding:4px 0 21px;font-size:15px;line-height:23px;color:#657087;"><strong style="color:#081538;">Opišite problem</strong> i priložite do pet fotografija, dokumenata ili PDF fajlova.</td></tr>
<tr><td width="48" valign="top"><div style="width:34px;height:34px;border-radius:50%;background:#00caf8;color:#061433;text-align:center;font-size:13px;line-height:34px;font-weight:800;">4</div></td><td style="padding:4px 0;font-size:15px;line-height:23px;color:#657087;"><strong style="color:#081538;">Pošaljite prijavu.</strong> Mi odmah dobijamo obaveštenje, a Vi pratite status.</td></tr></table></td></tr>

<tr><td class="px" style="padding:0 42px 44px;background:#ffffff;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#081538;border-radius:20px;overflow:hidden;"><tr><td style="padding:30px;border-left:5px solid #00caf8;"><div style="font-size:11px;line-height:14px;color:#00caf8;font-weight:800;letter-spacing:1.4px;text-transform:uppercase;">Naša obaveza prema Vama</div><div style="margin:9px 0 8px;font-size:24px;line-height:31px;color:#ffffff;font-weight:800;">Odgovor u roku od 24 sata.</div><div style="font-size:14px;line-height:23px;color:#cbd4e2;">Status pratite u realnom vremenu: <strong style="color:#ffffff;">Nova &rarr; U pregledu &rarr; U rešavanju &rarr; Rešena.</strong> Prepiska i konačno rešenje ostaju sačuvani na portalu.</div></td></tr></table></td></tr>

<tr><td class="px" align="center" style="padding:42px;background:#f8fafc;border-top:1px solid #e7ebf2;"><h2 style="margin:0 0 10px;font-size:26px;line-height:33px;letter-spacing:-.5px;color:#081538;">Vaša primedba je prilika da budemo bolji.</h2><p style="margin:0 auto 24px;max-width:480px;font-size:15px;line-height:24px;color:#657087;">Važno nam je da za problem saznamo — kako bismo mogli da ga rešimo i sprečimo da se ponovi.</p><table role="presentation" class="btn" align="center" cellspacing="0" cellpadding="0" border="0"><tr><td bgcolor="#00caf8" style="border-radius:999px;"><a href="https://gamaunited.rs/portal-za-klijente" target="_blank" style="display:inline-block;padding:15px 26px;color:#061433;font-size:15px;line-height:20px;font-weight:800;">Prijavite reklamaciju&nbsp;&nbsp;&rarr;</a></td></tr></table></td></tr>

<tr><td class="px" style="padding:27px 42px;background:#1b2b50;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td valign="top"><img src="${LOGO_WHITE}" width="128" alt="Gama United" style="display:block;width:128px;max-width:128px;height:auto;border:0;"><div style="margin-top:9px;font-size:11px;line-height:18px;color:#9eabc0;">Otona Župančiča 19, Novi Beograd<br>Radnim danima 08:00–22:00</div></td><td align="right" valign="top" style="font-size:11px;line-height:19px;color:#9eabc0;"><a href="tel:+38163237226" style="color:#dce3ed;">+381 63 237 226</a><br><a href="mailto:bojan.kresovic@gamaunited.rs" style="color:#dce3ed;">bojan.kresovic@gamaunited.rs</a><br><a href="https://gamaunited.rs" target="_blank" style="color:#00caf8;">gamaunited.rs</a></td></tr></table>
<!-- UNSUB_PLACEHOLDER --></td></tr>
</table><div style="max-width:600px;margin:15px auto 0;font-size:10px;line-height:16px;color:#8b95a5;text-align:center;font-family:Arial,'Helvetica Neue',Helvetica,sans-serif;">Ovu poruku ste dobili kao klijent kompanije Gama United.</div>
</td></tr></table></body></html>`;
